player-svc:
  build: ./goSvc
  working_dir: /go/src/
  command: go run main.go
  volumes:
    - ./goSvc/src/main.go:/go/src/main.go
    - ./goSvc/src/ddd:/go/src/ddd
  ports:
    - 8080:8080
#  links:
#    - player-db
  environment:
    - DB_NAME=players
    - DEBUG=true
#player-db:
#  image: postgres:latest
#  ports:
#    - "5432:5432"
#  environment:
#    - DEBUG=true
