player-svc:
  build: ./goSvc
  working_dir: /go/src/player-svc
  command: go run main.go
  volumes:
    - ./goSvc:/go/src/player-svc
    - ./goSvc/ddd:/go/src/player-svc/ddd
  ports:
    - 8080:8080
#  links:
#    - player-db
  environment:
    - DB_NAME=players
    - DEBUG=true
#player-db:
#  image: postgres:latest
#  ports:
#    - "5432:5432"
#  environment:
#    - DEBUG=true
