playerSvc:
  restart: always
  build: ./go-rest
  expose: 
    - "80"
  links: 
    - playersDb:playersDb
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app  
  environment:
    - DEBUG=true

data:
  volumes:
    - /var/lib/postgresql
  command: true
  environment:
    - DEBUG=true

playerDB:
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432" 
  environment:
    - DEBUG=true
