psvc:
  build: ./psvc/src/app
  working_dir: /go/src/
  command: go run app/main.go
  volumes: 
    - ./psvc/src/app/ddd:/go/src/app/ddd
  ports:
    - 8080:8080
  links:
    - player-db
  environment:
    - DB_NAME=players
    - DEBUG=true
player-db:
  image: postgres:latest
  ports:
    - "5432:5432"
  environment:
    - DEBUG=true
