DROP FUNCTION IF EXISTS fnGetPlayerSeason(integer);
DROP FUNCTION IF EXISTS fnGetPlayers(integer);
CREATE OR REPLACE FUNCTION fnGetPlayers() RETURNS TABLE (
  player_id integer,
  first_name text,
  last_name text,
  pos text,
  image_id bigint
) AS $$
    BEGIN
      RETURN QUERY SELECT
        id as player_id,
        p.first_name,
        p.last_name,
        p.pos,
        p.image_id
      FROM player p;
    END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fnGetPlayerSeason (in_player_id integer) RETURNS
  TABLE(
  player_id integer,
  start_year smallint,
  first_name text,
  last_name text,
  pos text,
  image_id bigint,
  End_Team char(3),
  GP smallint,
  ESG smallint,
  ESA smallint,
  ESP decimal(5, 2),
  ESP_60 decimal(5, 2),
  G55 smallint,
  A1_55 smallint,
  A2_55 smallint,
  ESShot smallint,
  ESMiss smallint,
  ESBlked smallint,
  ESChances smallint,
  ESSh_Per decimal(5, 2),
  ESCoSH_Per decimal(5, 2),
  ESTOI decimal(7,2),
  ESTOI_G decimal(5, 2),
  TOI_55 decimal(7,2),
  TOI_G_55 decimal(5,2),
  TOF_55 decimal(7,2),
  TOF_G_55 decimal(5,2),
  ES_Per decimal(5,2),
  ESPass smallint,
  ESBlk smallint,
  ESHitF smallint,
  ESHitA smallint,
  ESGive smallint,
  ESTake smallint,
  ESIGP decimal(5,2),
  ESIAP decimal(5,2),
  ESIPP decimal(5,2),
  ESOZFO smallint,
  ESOZ_Per decimal(5,2),
  ESDZFO smallint,
  ESDZ_Per decimal(5,2),
  ESNZFO smallint,
  ESNZ_Per decimal(5,2),
  OZ_Per decimal(5,2),
  OZRk smallint,
  RelOZ_Per decimal(5,2),
  ESOZF smallint,
  ESDZF smallint,
  ESNZF smallint,
  OZF_Per decimal(5,2),
  T_QoC decimal(5,2),
  T_QoC_Rk smallint,
  RCQoC decimal(5,3),
  QoCRk smallint,
  CQoC decimal(5,2),
  Cor_PerQoC decimal(5,2),
  T_QoT decimal(5,2),
  RCQoT decimal(5,2),
  CQoT decimal(5,2),
  Cor_PerQoT decimal(5,2),
  ESOISH_Per decimal(5,2),
  ESOISV_Per decimal(5,3),
  PDO smallint,
  SPD decimal(5,2),
  TmESGF_60 decimal(5,2),
  TmESGA_60 decimal(5,2),
  TmESSF_60 decimal(5,2),
  TmESSA_60 decimal(5,2),
  TmESCF_60 decimal(5,2),
  TmESCA_60 decimal(5,2),
  Corsi decimal(5,2),
  TmESGF smallint,
  TmESGA smallint,
  TmESSVA smallint,
  TmESSVF smallint,
  TmESMF smallint,
  TmESMA smallint,
  TmESBF smallint,
  TmESBA smallint,
  TmESSCF smallint,
  TmESSCA smallint,
  ESSC_Per decimal(5,2),
  ESRelSC_Per decimal(5,2),
  Adj_Corsi decimal(5,2),
  oTmESGF_60 decimal(5,2),
  oTmESGA_60 decimal(5,2),
  oTmESSF_60 decimal(5,2),
  oTmESSA_60 decimal(5,2),
  oTmESCF_60 decimal(5,2),
  oTmESCA_60 decimal(5,2),
  RelC decimal(5,2),
  oTmESGF smallint,
  oTmESGA smallint,
  oTmESSVA smallint,
  oTmESSVF smallint,
  oTmESMF smallint,
  oTmESMA smallint,
  oTmESBF smallint,
  oTmESBA smallint,
  ESPenT smallint,
  ESPenD smallint,
  ESPPD smallint,
  ESPenT_60 decimal(5,2),
  ESPenD_60 decimal(5,2),
  ESPPD_60 decimal(5,2),
  ExpGF smallint,
  ExpGA smallint,
  TmGFOff decimal(5,2),
  TmGAOff decimal(5,2),
  TmExpGFOff decimal(5,2),
  TmExpGAOff decimal(5,2),
  ESFOW smallint,
  ESFOL smallint,
  ESFO_Per decimal(5,2),
  ESOffFOT smallint,
  ESOffFOW smallint,
  ESOffFOSF smallint,
  ESOffFOSA smallint,
  ESOffNSPF decimal(5,2),
  ESOffFOGF smallint,
  ESOffFOGA smallint,
  ESOffNGPF decimal(5,2),
  ESDefFOT smallint,
  ESDefFOW smallint,
  ESDefFOSF smallint,
  ESDefFOSA smallint,
  ESDefNSPF decimal(5,3),
  ESDefFOGF smallint,
  ESDefFOGA smallint,
  ESDefNGPF decimal(5,3)
  )

AS $$
    BEGIN
    RETURN QUERY SELECT s.player_id,
      s.start_year,  
      p.first_name,
      p.last_name,
      p.pos,
      p.image_id,
      s.End_Team,
      s.GP,
      s.ESG,
      s.ESA,
      s.ESP,
      s.ESP_60,
      s.G55,
      s.A1_55,
      s.A2_55,
      s.ESShot,
      s.ESMiss,
      s.ESBlked,
      s.ESChances,
      s.ESSh_Per,
      s.ESCoSH_Per,
      s.ESTOI,
      s.ESTOI_G,
      s.TOI_55,
      s.TOI_G_55,
      s.TOF_55,
      s.TOF_G_55,
      s.ES_Per,
      s.ESPass,
      s.ESBlk,
      s.ESHitF,
      s.ESHitA,
      s.ESGive,
      s.ESTake,
      s.ESIGP,
      s.ESIAP,
      s.ESIPP,
      s.ESOZFO,
      s.ESOZ_Per,
      s.ESDZFO,
      s.ESDZ_Per,
      s.ESNZFO,
      s.ESNZ_Per,
      s.OZ_Per,
      s.OZRk,
      s.RelOZ_Per,
      s.ESOZF,
      s.ESDZF,
      s.ESNZF,
      s.OZF_Per,
      s.T_QoC,
      s.T_QoC_Rk,
      s.RCQoC,
      s.QoCRk,
      s.CQoC,
      s.Cor_PerQoC,
      s.T_QoT,
      s.RCQoT,
      s.CQoT,
      s.Cor_PerQoT,
      s.ESOISH_Per,
      s.ESOISV_Per,
      s.PDO,
      s.SPD,
      s.TmESGF_60,
      s.TmESGA_60,
      s.TmESSF_60,
      s.TmESSA_60,
      s.TmESCF_60,
      s.TmESCA_60,
      s.Corsi,
      s.TmESGF,
      s.TmESGA,
      s.TmESSVA,
      s.TmESSVF,
      s.TmESMF,
      s.TmESMA,
      s.TmESBF,
      s.TmESBA,
      s.TmESSCF,
      s.TmESSCA,
      s.ESSC_Per,
      s.ESRelSC_Per,
      s.Adj_Corsi,
      s.oTmESGF_60,
      s.oTmESGA_60,
      s.oTmESSF_60,
      s.oTmESSA_60,
      s.oTmESCF_60,
      s.oTmESCA_60,
      s.RelC,
      s.oTmESGF,
      s.oTmESGA,
      s.oTmESSVA,
      s.oTmESSVF,
      s.oTmESMF,
      s.oTmESMA,
      s.oTmESBF,
      s.oTmESBA,
      s.ESPenT,
      s.ESPenD,
      s.ESPPD,
      s.ESPenT_60,
      s.ESPenD_60,
      s.ESPPD_60,
      s.ExpGF,
      s.ExpGA,
      s.TmGFOff,
      s.TmGAOff,
      s.TmExpGFOff,
      s.TmExpGAOff,
      s.ESFOW,
      s.ESFOL,
      s.ESFO_Per,
      s.ESOffFOT,
      s.ESOffFOW,
      s.ESOffFOSF,
      s.ESOffFOSA,
      s.ESOffNSPF,
      s.ESOffFOGF,
      s.ESOffFOGA,
      s.ESOffNGPF,
      s.ESDefFOT,
      s.ESDefFOW,
      s.ESDefFOSF,
      s.ESDefFOSA,
      s.ESDefNSPF,
      s.ESDefFOGF,
      s.ESDefFOGA,
      s.ESDefNGPF
    FROM player p inner join season s on p.id=s.player_id WHERE p.id = in_player_id;

    
    END;
$$ LANGUAGE plpgsql;
