-- Table: player

DROP TABLE season;
DROP TABLE player;

CREATE TABLE player
(
  id serial PRIMARY KEY,
  -- player_compute text,
  first_name text,
  last_name text,
  pos text,
  -- date_of_birth date,
  image_id bigint
);
CREATE TABLE season
(
  id bigserial PRIMARY KEY,
  start_year smallint,
--  player_compute text,
--  start_year smallint,


  End_Team char(3),
  GP smallint,
  ESG smallint,
  ESA smallint,
  ESP decimal(5, 2),
  ESP_60 decimal(5, 2),
  G55 smallint,
  A1_55 smallint,
  A2_55 smallint,
  ESShot smallint,
  ESMiss smallint,
  ESBlked smallint,
  ESChances smallint,
  ESSh_Per decimal(5, 2),
  ESCoSH_Per decimal(5, 2),
  ESTOI decimal(7,2),
  ESTOI_G decimal(5, 2),
  TOI_55 decimal(7,2),
  TOI_G_55 decimal(5,2),
  TOF_55 decimal(7,2),
  TOF_G_55 decimal(5,2),
  ES_Per decimal(5,2),
  ESPass smallint,
  ESBlk smallint,
  ESHitF smallint,
  ESHitA smallint,
  ESGive smallint,
  ESTake smallint,
  ESIGP decimal(5,2),
  ESIAP decimal(5,2),
  ESIPP decimal(5,2),
  ESOZFO smallint,
  ESOZ_Per decimal(5,2),
  ESDZFO smallint,
  ESDZ_Per decimal(5,2),
  ESNZFO smallint,
  ESNZ_Per decimal(5,2),
  OZ_Per decimal(5,2),
  OZRk smallint,
  RelOZ_Per decimal(5,2),
  ESOZF smallint,
  ESDZF smallint,
  ESNZF smallint,
  OZF_Per decimal(5,2),
  T_QoC decimal(5,2),
  T_QoC_Rk smallint,
  RCQoC decimal(5,3),
  QoCRk smallint,
  CQoC decimal(5,2),
  Cor_PerQoC decimal(5,2),
  T_QoT decimal(5,2),
  RCQoT decimal(5,2),
  CQoT decimal(5,2),
  Cor_PerQoT decimal(5,2),
  ESOISH_Per decimal(5,2),
  ESOISV_Per decimal(5,3),
  PDO smallint,
  SPD decimal(5,2),
  TmESGF_60 decimal(5,2),
  TmESGA_60 decimal(5,2),
  TmESSF_60 decimal(5,2),
  TmESSA_60 decimal(5,2),
  TmESCF_60 decimal(5,2),
  TmESCA_60 decimal(5,2),
  Corsi decimal(5,2),
  TmESGF smallint,
  TmESGA smallint,
  TmESSVA smallint,
  TmESSVF smallint,
  TmESMF smallint,
  TmESMA smallint,
  TmESBF smallint,
  TmESBA smallint,
  TmESSCF smallint,
  TmESSCA smallint,
  ESSC_Per decimal(5,2),
  ESRelSC_Per decimal(5,2),
  Adj_Corsi decimal(5,2),
  oTmESGF_60 decimal(5,2),
  oTmESGA_60 decimal(5,2),
  oTmESSF_60 decimal(5,2),
  oTmESSA_60 decimal(5,2),
  oTmESCF_60 decimal(5,2),
  oTmESCA_60 decimal(5,2),
  RelC decimal(5,2),
  oTmESGF smallint,
  oTmESGA smallint,
  oTmESSVA smallint,
  oTmESSVF smallint,
  oTmESMF smallint,
  oTmESMA smallint,
  oTmESBF smallint,
  oTmESBA smallint,
  ESPenT smallint,
  ESPenD smallint,
  ESPPD smallint,
  ESPenT_60 decimal(5,2),
  ESPenD_60 decimal(5,2),
  ESPPD_60 decimal(5,2),
  ExpGF smallint,
  ExpGA smallint,
  TmGFOff decimal(5,2),
  TmGAOff decimal(5,2),
  TmExpGFOff decimal(5,2),
  TmExpGAOff decimal(5,2),
  ESFOW smallint,
  ESFOL smallint,
  ESFO_Per decimal(5,2),
  ESOffFOT smallint,
  ESOffFOW smallint,
  ESOffFOSF smallint,
  ESOffFOSA smallint,
  ESOffNSPF decimal(5,2),
  ESOffFOGF smallint,
  ESOffFOGA smallint,
  ESOffNGPF decimal(5,2),
  ESDefFOT smallint,
  ESDefFOW smallint,
  ESDefFOSF smallint,
  ESDefFOSA smallint,
  ESDefNSPF decimal(5,3),
  ESDefFOGF smallint,
  ESDefFOGA smallint,
  ESDefNGPF decimal(5,3),
  
  
  player_id integer REFERENCES player(id)
);
CREATE INDEX season_player ON season (player_id);